CREATE TABLE users (
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL,
	"email" TEXT UNIQUE NOT NULL,
	"password" TEXT NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT(now()) 
);
CREATE TABLE urls (
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER NOT NULL,
	"url" TEXT NOT NULL,
	"short" TEXT NOT NULL,
	"views" INTEGER NOT NULL DEFAULT(0),
	"createdAt" TIMESTAMP NOT NULL DEFAULT(now())
);
CREATE TABLE deletedurls (
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER NOT NULL,
	"urlId" INTEGER NOT NULL,
	"url" TEXT NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT(now())
);
CREATE TABLE sessions (
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER NOT NULL,
	"token" TEXT NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT(now())
);

ALTER TABLE "urls" ADD CONSTRAINT "urls_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "deletedurls" ADD CONSTRAINT "deletedurls_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "deletedurls" ADD CONSTRAINT "deletedurls_urlId_fkey" FOREIGN KEY ("urlId") REFERENCES "urls"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "sessions" ADD CONSTRAINT "deletedurls_urlId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;